const movieData = {
  title: "Movies",
  forceWords: ["Inception", "The Matrix"],
  items: [
    "Interstellar",
    "Oppenheimer",
    "Barbie",
    "Joker",
    "Tenet",
    "Dune",
    "Parasite",
    "John Wick",
    "Logan",
    "Deadpool",
    "Whiplash",
    "Get Out",
    "Arrival",
    "Gravity",
    "Memento",
    "Dunkirk",
    "1917",
    "Skyfall",
    "Gladiator",
    "Titanic",
    "Avatar",
    "The Dark Knight",
    "The Batman",
    "Black Panther",
    "Doctor Strange",
    "Thor Ragnarok",
    "Shutter Island",
    "Fight Club",
    "The Prestige",
    "La La Land",
    "Mad Max Fury Road",
    "Top Gun Maverick",
    "Blade Runner 2049",
    "Ex Machina",
    "A Quiet Place",
    "Knives Out",
    "Glass Onion",
    "Django Unchained",
    "Casino Royale",
    "The Departed",
    "Ford v Ferrari",
    "The Social Network",
    "Fury",
    "No Time to Die",
    "Iron Man",
    "Captain America",
    "The Revenant",
    "The Martian",
    "Star Wars",
    "Edge of Tomorrow"
  ]
};
